### ISSUE TITLE
Error: No Credentials Providers

### ISSUE THREAD

**Issue by iannuzzisean** [lynnlangit/Sagemaker-Spark-Scala#1]
I am getting the following error when attempting to run the steps.  

* provider.aws: error validating provider credentials: error calling sts:GetCallerIdentity: NoCredentialProviders: no valid providers in chain. Deprecated.

Specifically the following command generates this  error:
terraform plan -out /tmp/tfplan

**Comment by lynnlangit** [comment]
When I wrote this example only KOPS was available, now the native AWS credential provider is available for EKS.  To get this example to work, you would have to either a) download and configure KOPS or b) refactor the template to use AWS cred provider.  Here's more context -- https://stackoverflow.com/questions/51445566/kops-over-aws-eks-or-vice-versa

**Comment by iannuzzisean** [comment]
Thanks.  The solution was to modify the main.tf file with the following information per the AWS access key and secret.

# Configure the AWS Provider
provider "aws" {
  access_key = "${var.aws_access_key}"
  secret_key = "${var.aws_secret_key}"
  region     = "us-east-1"
}
